camera_info:
  focal_length_x: 1345.200806
  focal_length_y: 1353.838257
  image_width: 800
  image_height: 600
stop_line_positions:
    - [20.991, 22.837]
tl:
  tl_classification_model: 'models/tl_classifier_carla.h5'
  tl_detection_model: 'models/tl_detector_carla.h5'
  classifier_resize_height: 64
  classifier_resize_width: 32
  detector_resize_width: 128
  detector_resize_height: 96
  projection_threshold: 2
  projection_min: 200
  detector_rate: 20
  is_carla: true
  color_mode: 'rgb8'
